name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup JDK 23
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 23

    - name: Install and configure ccache
      run: |
        sudo apt-get update
        sudo apt-get install -y ccache
        export CCACHE_DIR=$HOME/.ccache
        export CCACHE_COMPRESS=true
        export CCACHE_MAXSIZE=500M
        export PATH="/usr/lib/ccache:$PATH"

    - name: Cache ccache
      uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: ccache-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ccache-${{ runner.os }}-gradle-

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug
      env:
        ANDROID_NON_TRANSITIVE_R_CLASS: true
        ORG_GRADLE_JVMARGS: "-Dorg.gradle.java.home=${{ env.JAVA_HOME }}"
        ORG_GRADLE_CACHING: true

    - uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Create release
      uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/master'
      with:
        repo_token: ${{ secrets.TOKEN_PASS }}
        automatic_release_tag: "latest"
        prerelease: false
        title: ${{ github.sha }}
        files: |
          app/build/outputs/apk/debug/app-debug.apk
